### ISSUE TITLE
Unable to install pytrial python library due to dependency conflicts

### ISSUE THREAD

**Issue by 228rajesh** [RyanWangZf/PyTrial#6]
While installing pytrial python library, i'm facing below listed dependency issues.
Please help me to resolve these dependency issues
Thanks !! 

ERROR: Cannot install pytrial==0.0.1, pytrial==0.0.2 and pytrial==0.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    pytrial 0.0.3 depends on copulas==0.7.0
    pytrial 0.0.2 depends on copulas==0.7.0
    pytrial 0.0.1 depends on copulas==0.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by RyanWangZf** [comment]
Hi, can you try to clone the repo to your local environment to remove the version requirement of copulas? Then you can install it using `pip install .` ; please let me know if it solves the problem.

Zifeng

**Comment by 228rajesh** [comment]
Hi @RyanWangZf,
Thanks for the reply
I cloned the repo to my local environment but still it is not working
Kindly, guide me through the step-by-step process to install it successfully.

**Comment by RyanWangZf** [comment]
Hi, can you try to install it from GitHub again and does it still raise an error? Thx.

**Comment by SaraiQX** [comment]
Hi there,
Many thanks to the team for the amazing work!
Just to share my experience re the installation process.
I tried both macbookpro (intel) and the linux GPU env in the cloud and I found the "git clone.." way works easier.
For mbp, 
```
Python 3.7.16
torch    1.13.1 
```
The local mac env works a bit slow. 
For linux on the cloud (3080):
```
Python 3.7.16
pytorch   1.12.1
```
And the env works okay.
